### ISSUE TITLE
Option to automatically import hashed/versioned workbox-sw in injectManifest mode

### ISSUE THREAD

**Issue by codepunkt** [GoogleChrome/workbox#795]
**Library Affected**:
*workbox-build*

**Issue or Feature Request Description**:
I'm using workbox with webpack and provide an `swSrc` option in my webpack configuration because i want to do custom stuff in my service worker that can not be auto generated. I also use [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin) to copy the current version of the `workbox-sw` module to my build output so i can import it from my serviceWorker.

```javascript
// Snippet 1: interesting part of webpack config
plugins: [
  new CopyWebpackPlugin([
    {
      from: require.resolve('workbox-sw'),
      to: './dist/client/workbox-sw.js',
    },
  ]),
  new WorkboxPlugin({
    globDirectory: './dist/client',
    globPatterns: ['**/*.{js}'],
    swSrc: './src/client/serviceWorker.js',
    swDest: './dist/client/serviceWorker.js',
  }),
]
```

```javascript
// Snippet 2: serviceWorker.js source without the custom logic
importScripts('workbox-sw.js')

const workboxSW = new WorkboxSW()
workboxSW.precache([])
```

I would like to have the version number of `workbox-sw` or a hash of it's file contents in it's file name as a cache buster because as it is, the file is cached and the installed service worker is not updated unless the content of `serviceWorker.js` itself changes. I can easily do that by using `file-loader` patterns in the copy plugin configuration, such as this:

```javascript
// Snippet 3: Copy workbox-sw with hashed filename
new CopyWebpackPlugin([
  {
    from: require.resolve('workbox-sw'),
    to: './dist/client/workbox-sw.[sha512:hash:base64:8].js',
  },
]),
```

Every time the content of the resolved `workbox-sw` module changes, a file with a new hash is created. What is missing to automatically update the contents of the generated `serviceWorker.js` based on that update is a way to somehow add the `importScripts` line from Snippet 2 using `workbox-webpack-plugin` so this doesn't get me any further.

My idea: Provide an option for `workbox-build` that copies the current version of `workbox-sw` to a hashed/versioned file next to the `swDest` file when using injectManifest mode and automatically add an `importScript` line for that file at the beginning of the `swDest` contents.

Any opinions/suggestions?

**Comment by codepunkt** [comment]
Related to #650, #654, #672

**Comment by jeffposnick** [comment]
CC: @goldhand for his thoughts, as there's a lot of Webpack specifics in there.

**Comment by goldhand** [comment]
Currently planning to add workbox-sw as a webpack asset during the compilation. Good point about versioning. I can use webpack to add a hash during build. But this still doesn't solve for existing service workers.

I like your suggestion's @codepunkt and I think it will work will work. I think we can easily add that importScripts to the existing service worker during compilation and include that option in the webpack plugin, or is that what you meant?

I was thinking it would be nice if we could import `workbox-sw` using some kind of serviceworker loader that supports importing modules into workers or something.

**Comment by codepunkt** [comment]
Yes, basically that's what i meant:

- add workbox-sw (optionally with [hash] etc `file-loader` syntax for the filename) as a webpack asset during compilation
- add an option to the webpack plugin that allows you to insert an `importScript('filename-of-webpack-sw-asset.js')` to the serviceWorker.

**Comment by gauntface** [comment]
+1 all of the above.

@codepunkt would you want to add the importScript yourself, or would you want a tool to add it for you?

**Comment by codepunkt** [comment]
rephrasing my second bullet-point:

- add an option to the webpack plugin that allows it to automatically insert an `importScript('filename-of-webpack-sw-asset.js')` at the first line of the serviceWorker.

**Comment by goldhand** [comment]
Thinking maybe a webpack-loader *(rather than a webpack-plugin)* would be effective here. Just thinking, it could transform `module.exports = foo;` to `self.foo = foo;` and `const foo = require('./foo');` to `const foo = self.foo;` or something like that.

@codepunkt a side note: the proposal in #808 will just prepend a versioned `workbox-sw` to your existing service worker. I think that will solve for the original issue.

**Comment by gauntface** [comment]
@jeffposnick @goldhand this sounds like it's fixed in v3 - but not sure.

**Comment by jeffposnick** [comment]
I am not 100% sure either. I've been focusing more efforts on the use case when `swSrc` is not specified (i.e. the generate SW use case) then when it is specified, which is a use case that this issue tracks.

We might be able to roll this up into https://github.com/GoogleChrome/workbox/issues/933, though, to at least consolidate the discussion. @codepunkt does it sound like that issue covers some of the same ground?

**Comment by gauntface** [comment]
Well the new workbox webpack plugin can be tests here:

```
npm install --save-dev workbox-webpack-plugin@3.0.0-alpha.2
```

@codepunkt if you get a chance to try it out it would definitely help to figure out if we are closer to what you were looking for.

**Comment by stenmuchow** [comment]
@gauntface I just ran into this issue as well, the new 3.0.0 alpha seems to be acceptable in so far as what it creates. I do however when debugging on firefox locally (we have proxied localhost urls and chrome is too cranky to allow this) get a network error when it tries to import the workbox-cdn url... 

It seems to not want to allow me to download this resource... :/

**Comment by jeffposnick** [comment]
@stenmuchow, can you provide the exact URL that's requested and failing, the proxy configuration you're using with Firefox, and a screenshot/text of the failure message?

**Comment by stenmuchow** [comment]
Further findings for the alpha release... When pushed onto our development server with a valid SSL cert, I can test it on chrome and there are no issues with the package. However there are issues with your documentation now. 

As I am trying to create my own service worker, following the guide set forth in [Step 6](https://developers.google.com/web/tools/workbox/get-started/webpack#inject)
I have a naming collision of workbox being defined in two places. One in my service worker file that I am making and the other in workbox-sw.js from the importScripts url. 

![screen shot 2017-12-08 at 8 12 54 am](https://user-images.githubusercontent.com/3219270/33756928-b431a600-dbef-11e7-8d69-74a16193f386.png)

**Comment by stenmuchow** [comment]
@jeffposnick Firefox debugging....

Failing URL - https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-sw.js
But this is only locally... 

**Proxy config**
URL: http://logistics.softwearconnect.lc

**etc/host**
127.0.0.1       logistics.softwearconnect.lc

**nginx** to serve from my dist dir
```     
     server {
	listen 80;
	listen [::]:80;
	server_name  ~logistics.softwearconnect.lc$;
        root /Users/Work/dist/logistics;

       location / {
         try_files $uri $uri/ =404;
       }

       location /dist {
         alias /Users/Work/dist/logistics;
       }
     }
```

Then following the service worker debugging on FF localhost. 

Advanced Settings in dev tools I "Enable Service Workers over HTTP when devtools is open"

Now since I have fixed the naming collision that occurred in the previous comment above i now get an error saving WorkBoxSW is not defined.

<img width="769" alt="screen shot 2017-12-08 at 8 26 33 am" src="https://user-images.githubusercontent.com/3219270/33757321-8d8574da-dbf1-11e7-9b50-2a3c37578121.png">

Which then takes me to this line:

<img width="1296" alt="screen shot 2017-12-08 at 8 27 13 am" src="https://user-images.githubusercontent.com/3219270/33757367-bbac97e4-dbf1-11e7-89cf-952996bb5b0a.png">

Previously before the naming collision took place it looked like the following...

<img width="764" alt="screen shot 2017-12-08 at 8 33 16 am" src="https://user-images.githubusercontent.com/3219270/33757527-7e86b83a-dbf2-11e7-9eae-9c6cb0df91f1.png">

Which then takes me to this line:

<img width="1310" alt="screen shot 2017-12-08 at 8 33 47 am" src="https://user-images.githubusercontent.com/3219270/33757552-9865329a-dbf2-11e7-9000-d65542cfea76.png">

Hope that helps point in some direction...

**Comment by stenmuchow** [comment]
Then upon further research it seems the API is massively altered so the most of my comments are mute. 

Based on these [docs](https://developers.google.com/web/tools/workbox/reference-docs/v3.0.0-alpha.1/)...

My created sw file looks like this now:

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.0.0-alpha.2/workbox-sw.js', 'precache-manifest.a21c7ec6a5490a5a9460ca95538867b3.js');
'use strict';

workbox.skipWaiting();
workbox.clientsClaim();

const swWorkbox = new workbox.routing.Router();

swWorkbox.registerRoute(
  new RegExp('.+SKUS\.JS.+'),
  workbox.strategies.staleWhileRevalidate()
);

```

This has managed to make my errors go away and the files to download properly, but i seem to have lost all functionality of the SW.

**Comment by gauntface** [comment]
@stenmuchow thanks for sticking with us on this (and it sounds like we are moving in the right direction).

Can you share the Webpack code you are using and just to check - you are running 3.0.0-alpha.2 for your webpack plugin.

**Comment by jeffposnick** [comment]
To avoid confusion, ensure that you're looking at material at https://developers.google.com/web/tools/workbox/next/ as that's what applies to the current alpha release. (And in case you missed it, the [3.0 alpha release notes](https://github.com/GoogleChrome/workbox/releases/tag/v3.0.0-alpha.2) give a broad outline of what changed.)

Going to your second example, for a second, you write:

```
workbox.precaching.precacheAndRoute([]); // <----- NOTHING SEEMS TO BE INJECTED?
```

We need to improve the docs here (https://github.com/GoogleChrome/workbox/issues/1110); if you're providing your own service worker file to the webpack plugin via `swSrc`, then the syntax to use is

```js
workbox.precaching.precacheAndRoute(self.__precacheManifest)`
```

(This matches what you'd get if you started from scratch with `generateSW` in v3, but not everyone will follow that flow.)

**Comment by stenmuchow** [comment]
@gauntface - No problem, it's in my best interest to get this working ;) Or at least I can feel good about myself in someway... 🤔 

I guess this is the only interesting part from my webpack config...

``` new WorkboxPlugin({
      globDirectory: DIST_DIR,
      globPatterns: ['**/*.{html,js,css,png,ttf,eot,woff,woff2,svg}'],
      swDest: path.join(DIST_DIR, 'sw.js'),
      swSrc: path.join('service-worker', 'sw.js'),
      maximumFileSizeToCacheInBytes: 10000000 //10MB
    })```

Or here is a [gist](https://gist.github.com/stenmuchow/7a4753503b4531cb34a2dde020ed3dca) or the whole deal... 

Also maybe this from my package.json

`"workbox-webpack-plugin": "^3.0.0-alpha.2"`

Pretty sure I am using it how it should be used...

**Comment by stenmuchow** [comment]
@jeffposnick Indeed I am looking at those docs...

Based on the info found [here](https://developers.google.com/web/tools/workbox/guides/precache-files)

<img width="988" alt="screen shot 2017-12-08 at 8 04 50 pm" src="https://user-images.githubusercontent.com/3219270/33783129-4469ffac-dc53-11e7-807d-1951e0bb4e60.png">

I followed that piece of logic to determine the setup, or the auto inject.\

Never-the-less looking at this...

`workbox.precaching.precacheAndRoute(self.__precacheManifest)`

...kinda makes complete sense as thats what the precacheManifest file array is assigned to. 

🙈 Covering my eyes and following the docs! 😄 

Thanks again for all the hard work @jeffposnick and @gauntface and the rest of your gang...

**Comment by gauntface** [comment]
@stenmuchow this is partly my fault. No one has written anything for the webpack config and I don't know how it's meant to be used so I left it, but I also didn't realise there was a completely different behaviour, I'll try adding something now just so it's clear it's different.

**Comment by jeffposnick** [comment]
https://github.com/google/WebFundamentals/pull/5498/files#diff-de2ecb2b4b7018b1cbd91913f18500e5R95 should also help here.

**Comment by gauntface** [comment]
I'm going to close this issue - Jeff has done a tonne of work on the web pack plugin (along with others) and the docs are in a better place than when this PR was raised so fingers crossed we've answered the issues raised here and if not - please open new issues with problems as they arise.
